# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-18 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_present',
            field=models.ImageField(blank=True, null=True, upload_to='static/slavatur/db_img', verbose_name='картинка вместо видео для телефонов'),
        ),
    ]
