# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-19 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190218_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='video_present',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='text_on_video',
            new_name='title',
        ),
    ]
