# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-19 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190219_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Заголовок'),
        ),
    ]
