# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-19 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190219_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_present',
            field=models.ImageField(blank=True, null=True, upload_to='static/slavatur/db_img', verbose_name='Картинка'),
        ),
    ]
