# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя отправителя')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст отзыва')),
                ('show', models.BooleanField(default=True, verbose_name='показывать на сайте')),
                ('image_present', models.ImageField(blank=True, null=True, upload_to='db_img', verbose_name='Фото для отзыва')),
            ],
        ),
    ]
