# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190207_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='image_present',
            field=models.ImageField(blank=True, null=True, upload_to='db_img', verbose_name='картинка вместо видео для телефонов'),
        ),
    ]
