# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-17 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20190217_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image_present',
            new_name='image',
        ),
    ]
