# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-27 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20190217_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='credentials',
            new_name='fio',
        ),
        migrations.AddField(
            model_name='comment',
            name='view',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='db_img', verbose_name='Фотография для отзыва'),
        ),
    ]
