# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-04 12:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_on_video', models.CharField(blank=True, max_length=25, null=True, verbose_name='надпись на видео')),
                ('video_present', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
                ('image_present', models.ImageField(blank=True, null=True, upload_to='db_img', verbose_name='картинка вместо видео для телефонов')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='порядок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='текст')),
                ('slug', models.SlugField(max_length=255, verbose_name='слаг')),
                ('image_present', models.ImageField(blank=True, null=True, upload_to='db_img', verbose_name='картинка')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='main.MainText', verbose_name='модуль')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
