# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-07 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='db_img', verbose_name='изображение')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('credentials', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
                'verbose_name': 'Комментарий',
            },
        ),
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_on_video', models.CharField(blank=True, max_length=25, null=True, verbose_name='надпись на видео')),
                ('video_present', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
                ('image_present', models.ImageField(blank=True, null=True, upload_to='db_img', verbose_name='картинка вместо видео для телефонов')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=25, null=True, verbose_name='Надпись на картинке')),
                ('slug', models.SlugField(max_length=255, verbose_name='слаг')),
                ('image_present', models.ImageField(blank=True, null=True, upload_to='db_img', verbose_name='картинка')),
            ],
        ),
    ]
