# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-07 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='MainText',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
