# Generated by Django 2.1.5 on 2019-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190205_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='text',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='надпись на видео'),
        ),
    ]
